version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lecture_qa_postgres
    environment:
      POSTGRES_USER: lecture_qa
      POSTGRES_PASSWORD: lecture_qa123
      POSTGRES_DB: lecture_qa_db
    ports:
      - "5433:5432"  # 호스트의 5433 포트를 컨테이너의 5432 포트에 매핑
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 