services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lecture_qa_fastapi
    volumes:
      - video_uploads:/app/uploads
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: lecture_qa_nginx
    ports:
      - "80:80"
    volumes:
      - video_uploads:/usr/share/nginx/html/uploads
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    restart: unless-stopped
    networks:
      - app-network

volumes:
  video_uploads:

networks:
  app-network:
    driver: bridge